#include "hal_data.h"
#include "app/APP_MOTOR.h"
#include "app/app_uart.h"
#include "bsp/bsp_encoder.h"
#include "bsp/bsp_uart.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
    g_hal_init();
    uart_bsp_init();
    encoder_bsp_init();
    app_motor_init();
    app_motor_set_sensor_invert(0U);

#if (0U != HAL_TRACK_DEBUG_UART)
    car_uart_track_debug_boot_msg();
#endif

#ifndef HAL_LINE_FOLLOW_BASE_SPEED
#define HAL_LINE_FOLLOW_BASE_SPEED (15.0f)
#endif
#ifndef HAL_LINE_FOLLOW_PERIOD_MS
#define HAL_LINE_FOLLOW_PERIOD_MS (10U)
#endif
    {
        const float dt_sec = (float)HAL_LINE_FOLLOW_PERIOD_MS / 1000.0f;
        uint8_t     was_halted = 0U;

        for ( ; ; )
        {
            /* 字节由 UART RXI 中断入环缓，此处仅解析命令并更新 g_car_stop_request */
            car_uart_command_poll();
#if (0U != HAL_TRACK_DEBUG_UART)
            car_uart_track_periodic_poll((uint32_t)HAL_LINE_FOLLOW_PERIOD_MS);
#endif

            if (0U != car_uart_halted_get()) {
                /* STOP：边沿触发一次刹车，避免每周期重复 app_motor_stop 清 PID */
                if (0U == was_halted) {
                    app_motor_stop();
                }
                was_halted = 1U;
                encoder_bsp_velocity_sample(dt_sec);
                R_BSP_SoftwareDelay(HAL_LINE_FOLLOW_PERIOD_MS, BSP_DELAY_UNITS_MILLISECONDS);
                continue;
            }

            /* RUN：从停机恢复时清 PID，避免长时间停积分的突变（可按实车删掉） */
            if (0U != was_halted) {
                app_motor_pid_reset();
            }
            was_halted = 0U;

            //encoder_bsp_velocity_sample(dt_sec);
            //禁用内环后不需要编码器测量速度，减少CPU负担。
            app_motor_line_follow_update(HAL_LINE_FOLLOW_BASE_SPEED, dt_sec);
            R_BSP_SoftwareDelay(HAL_LINE_FOLLOW_PERIOD_MS, BSP_DELAY_UNITS_MILLISECONDS);
        }
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
